# Generated by Django 3.0.8 on 2020-09-06 13:50

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200906_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dataRemovedDate',
            field=models.DateField(default=datetime.date(2020, 9, 6), verbose_name='data removed date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null='user54181', unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
