# Generated by Django 3.0.8 on 2020-09-11 21:29

import datetime
import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200906_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dataRemovedDate',
            field=models.DateField(default=datetime.date(2020, 9, 11), verbose_name='data removed date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null='user36383', unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
