# Generated by Django 3.0.8 on 2020-09-25 23:54

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200925_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dataRemovedDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data removed date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null='user84953', unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
