# Generated by Django 3.0.8 on 2020-09-26 00:14

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200926_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dataRemovedDate',
            field=models.DateField(auto_now_add=True, verbose_name='data removed date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null='user76411', unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
